# Test configuration to verify GraphQL traffic control
loadTest:
  virtualUsers: 3
  sustainedDuration: "15s"

trafficDistribution:
  homepage: 0.9
  categoryPages: 0.5
  productPages: 0.5
  searchResults: 0.1
  cartPages: 0.3
  checkoutPages: 0.2
  addToCartActions: 0.3
  
  # INCREASED GRAPHQL FOR TESTING
  graphqlRequests: 0.3              # 30% GraphQL traffic (increased from 5%)
  restApiRequests: 0.2              # 20% REST API traffic (increased from 5%)
  
  customerAccount: 0.05
  wishlistPages: 0.02
  productComparison: 0.03
  layeredNavigation: 0.1
  cmsPages: 0.02
  contactPages: 0.01
  ajaxRequests: 0.1
  mediaRequests: 0.1

api:
  enableApiLoad: true
  enableGraphqlLoad: true
  enableRestLoad: true

urlDiscovery:
  enableUrlDiscovery: false
  enableFallbackUrls: true

realUrls:
  fallbackCategorySlugs:
    - "category-4"
    - "category-5"
    - "gear"
  realProductUrls:
    - "radiant-tee.html"
    - "breathe-easy-tank.html"
    - "hero-hoodie.html"
  fallbackSearchTerms:
    - "shirt"
    - "pants"
    - "shoes"
